"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.EventName = exports.SupportedNetwork = void 0;
var SupportedNetwork;
(function (SupportedNetwork) {
    SupportedNetwork["Avalanche"] = "Avalanche";
    SupportedNetwork["Ethereum"] = "Ethereum";
    SupportedNetwork["Base"] = "Base";
    SupportedNetwork["Arbitrum"] = "Arbitrum";
})(SupportedNetwork || (exports.SupportedNetwork = SupportedNetwork = {}));
var EventName;
(function (EventName) {
    EventName["WALLET_CONNECTION_ATTEMPTED"] = "Wallet Connection Attempted";
    EventName["WALLET_CONNECTION_SUCCESS"] = "Wallet Connection Success";
    EventName["WALLET_CONNECTION_FAILED"] = "Wallet Connection Failed";
    EventName["NETWORK_SWITCH_REQUESTED"] = "Network Switch Requested";
    EventName["NETWORK_ADDED"] = "Network Added";
    EventName["WALLET_CREATION_STARTED"] = "Wallet Creation Started";
    EventName["WALLET_CREATION_SUCCESS"] = "Wallet Creation Success";
    EventName["WALLET_CREATION_FAILED"] = "Wallet Creation Failed";
    EventName["TRANSACTION_INITIATED"] = "Transaction Initiated";
    EventName["TRANSACTION_VALIDATION_STARTED"] = "Transaction Validation Started";
    EventName["TRANSACTION_MODE_SELECTED"] = "Transaction Mode Selected";
    EventName["TRANSACTION_SUCCESS"] = "Transaction Success";
    EventName["TRANSACTION_FAILED"] = "Transaction Failed";
    EventName["WALLET_SELECTED"] = "Wallet Selected";
    EventName["WALLET_DESELECTED"] = "Wallet Deselected";
    EventName["NETWORK_CHANGED"] = "Network Changed";
    EventName["CREATE_WALLET_BUTTON_CLICKED"] = "Create Wallet Button Clicked";
    EventName["ADDRESS_COPY_CLICKED"] = "Address Copy Clicked";
    EventName["WALLET_SORT_CHANGED"] = "Wallet Sort Changed";
    EventName["PROFILE_EDIT_STARTED"] = "Profile Edit Started";
    EventName["PROFILE_NAME_CHANGED"] = "Profile Name Changed";
    EventName["PROFILE_PICTURE_CHANGED"] = "Profile Picture Changed";
    EventName["PROFILE_EDIT_SAVED"] = "Profile Edit Saved";
    EventName["WALLET_NAME_EDIT_STARTED"] = "Wallet Name Edit Started";
    EventName["WALLET_NAME_CHANGED"] = "Wallet Name Changed";
    EventName["WALLET_NAME_EDIT_SAVED"] = "Wallet Name Edit Saved";
    EventName["EXPORT_WALLETS_CLICKED"] = "Export Wallets Clicked";
    EventName["IMPORT_WALLETS_CLICKED"] = "Import Wallets Clicked";
    EventName["IMPORT_FILE_SELECTED"] = "Import File Selected";
    EventName["LOGOUT_CLICKED"] = "Logout Clicked";
    EventName["NAVIGATION_CLICKED"] = "Navigation Clicked";
    EventName["POLICY_VIEWED"] = "Policy Viewed";
})(EventName || (exports.EventName = EventName = {}));
//# sourceMappingURL=types.js.map